; fltMiniOLEDClock - PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
; Copyright (c) 2025-2026 by HA3FLT

[env]
build_flags =
	-D FMOC_VERSION_NUMBER=132
	-D FMOC_DEBUG_WEB_SERVER=1
    -D FMOC_HTTPS_SERVER_PORT=24443
    -D FMOC_DEFAULT_DEVICE_LOCATION=\"Bathroom\ unit\"
    -D FMOC_TIME_ZONE_OFFSET_MINS=60
	-D FMOC_SENSORS_UPDATES_INTERVAL_SEC=60
    -D FMOC_DEFAULT_ALTITUDE_METERS=120
    -D FMOC_MEASURED_RAW_PA=99750
    -D FMOC_REFERENCE_SEA_LEVEL_PA=101400

[platformio]
src_dir = src

[env:wemos_d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = colorize
lib_deps = 
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.2
	adafruit/Adafruit BMP085 Library @ ^1.2.4
	paulstoffregen/Time@^1.6.1
	milesburton/DallasTemperature@^4.0.6
lib_ignore = info_nocomp
